
/*
 * generated by Xtext
 */
 
package org.storydriven.modeling.expressions.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class PathExpressionsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.storydriven.modeling.expressions.ui.internal.PathExpressionsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.storydriven.modeling.expressions.ui.internal.PathExpressionsActivator.getInstance().getInjector("org.storydriven.modeling.expressions.PathExpressions");
	}
	
}
