/*
 * generated by Xtext
 */
package org.storydriven.modeling.expressions.common;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExpressionsRuntimeModule extends org.storydriven.modeling.expressions.common.AbstractExpressionsRuntimeModule {

}
