/*
 * generated by Xtext
 */
package org.storydriven.modeling.expressions.common.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExpressionsUiModule extends org.storydriven.modeling.expressions.common.ui.AbstractExpressionsUiModule {
	public ExpressionsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
