<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modeling"
    nsURI="http://ns.storydriven.org/sdm/0.1.0" nsPrefix="sdm">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="The modeling package is the root package for the SDM meta-model. It defines several abstract super classes which implement an extension mechanism as well as reoccuring structural features like, e.g., names of elements. The classes in this package are intended to be sub-classed by any meta-model element."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="TypedElement" abstract="true" eSuperTypes="#//ExtendableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract super class for all meta-model elements that are typed by means of an EClassifier or an EGenericType."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" ordered="false" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="union"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="genericType" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EGenericType"
        unsettable="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtendableElement" abstract="true" eSuperTypes="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for the whole SDM model. The ExtendableElement specifies the extension mechanism that can be used to extend an object by an Extension containing additional attributes and references."/>
    </eAnnotations>
    <eOperations name="getExtension" ordered="false" lowerBound="1" eType="#//Extension">
      <eParameters name="type" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eOperations name="provideExtension" ordered="false" lowerBound="1" eType="#//Extension">
      <eParameters name="type" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass"/>
    </eOperations>
    <eOperations name="getAnnotation" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAnnotation">
      <eParameters name="source" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="provideAnnotation" ordered="false" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAnnotation">
      <eParameters name="source" ordered="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" ordered="false"
        upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAnnotation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extension" ordered="false"
        upperBound="-1" eType="#//Extension" containment="true" eOpposite="#//Extension/extendableBase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Extension" abstract="true" eSuperTypes="#//ExtendableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract super class for an Extension that can be defined for an object."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="base" ordered="false" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject"
        changeable="false" volatile="true" transient="true" derived="true">
      <eAnnotations source="union"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelBase" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EModelElement"
        volatile="true" transient="true" unsettable="true" derived="true">
      <eAnnotations source="subsets" references="#//Extension/base"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owningAnnotation" ordered="false"
        eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAnnotation"
        volatile="true" transient="true" unsettable="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendableBase" ordered="false"
        eType="#//ExtendableElement" eOpposite="#//ExtendableElement/extension">
      <eAnnotations source="subsets" references="#//Extension/base"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommentableElement" abstract="true"
      eSuperTypes="#//ExtendableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract super class for all meta-model elements that may carry a comment in form of a string."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true" eSuperTypes="#//TypedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Represents a variable which can be, for example, an object variable, an attribute, or any other kind of variable."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" eSuperTypes="#//ExtendableElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract super class for all meta-model elements that carry a name. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The name attribute of a meta-model element."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eSubpackages name="activities" nsURI="http://ns.storydriven.org/sdm/activities/0.1.0"
      nsPrefix="sdma">
    <eClassifiers xsi:type="ecore:EClass" name="ExceptionVariable" eSuperTypes="#//Variable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Declares a variable representing an Exception that leads to firing a transition (ActivityEdge). Can only be applied to ActivityEdge whose guard is set to EXCEPTION."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="activityEdge" ordered="false"
          lowerBound="1" eType="#//activities/ActivityEdge" eOpposite="#//activities/ActivityEdge/guardException">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Specifies the transition (activity edge) where the exception variable is declared."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Specifies the name of the declared exception variable."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exceptionType" ordered="false"
          upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"
          transient="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Specifies the type of the declared exception variable."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="genericExceptionType"
          ordered="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EGenericType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge" eSuperTypes="#//ExtendableElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The ActivityEdge represents the control flow in an activity. It is a dericted connection from one activity to another one. There exist different kinds of activity edges which are differentiated by the guard attribute."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
          lowerBound="1" eType="#//activities/ActivityNode" eOpposite="#//activities/ActivityNode/incoming">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The target node of this ActivityEdge."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" eType="#//activities/ActivityNode" eOpposite="#//activities/ActivityNode/outgoing">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The source node of this ActivityEdge."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningActivity" ordered="false"
          lowerBound="1" eType="#//activities/Activity" eOpposite="#//activities/Activity/ownedActivityEdge">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Points to the activity this ActivityEdge is contained in."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="guard" ordered="false"
          lowerBound="1" eType="#//activities/EdgeGuard" defaultValueLiteral="NONE">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The guard defines the kind of the activity edge. The possible kinds of guards are specified by the EdgeGuard enum."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="guardExpression" ordered="false"
          eType="#//expressions/Expression" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Points to an expression in case the transition guard is BOOL. The expression has to evaulate to a boolean value."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="guardException" upperBound="-1"
          eType="#//activities/ExceptionVariable" containment="true" eOpposite="#//activities/ExceptionVariable/activityEdge">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Declares variables representing the Exceptions that lead to firing this transition."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityNode" abstract="true" eSuperTypes="#//NamedElement #//CommentableElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Abstract super class for all kinds of nodes that may be added to an activity. This class provides the basic functionality of connecting the activity nodes in the activity by ActivityEdges."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" ordered="false"
          upperBound="-1" eType="#//activities/ActivityEdge" eOpposite="#//activities/ActivityEdge/source">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="All ActivityEdges that leave this activity node. The guards of the outgoing activity edges must be exclusive in order to obtain a well-defined activity."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningActivity" ordered="false"
          eType="#//activities/Activity" eOpposite="#//activities/Activity/ownedActivityNode">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Points to the activity this ActivityNode is contained in."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningActivityNode" ordered="false"
          eType="#//activities/StructuredNode" eOpposite="#//activities/StructuredNode/ownedActivityNode">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The parent node if this node is contained in a StructuredNode."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" ordered="false"
          upperBound="-1" eType="#//activities/ActivityEdge" eOpposite="#//activities/ActivityEdge/target">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="All ActivityEdges entering this activity node."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//CommentableElement #//calls/Callable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The diagram that describes the control flow of an operation. It is used to structure a number story patterns into a stroy diagram. Story patterns are contained in activity nodes which are connected by activity edges. In addition, there are special nodes like start, stop, and juction nodes.  "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="owningOperation" ordered="false"
          eType="#//activities/OperationExtension" eOpposite="#//activities/OperationExtension/ownedActivity"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivityEdge" upperBound="-1"
          eType="#//activities/ActivityEdge" containment="true" eOpposite="#//activities/ActivityEdge/owningActivity">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="All ActivityEdges that are contained in this activity."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" ordered="false"
          eType="#//activities/MatchingStoryNode">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="References a story node which represents the precondition for the execution of the activity. I.e., the activity is executed, iff the object structure in the story node can be matched. Obviously the referenced story node may only contain black (i.e., non-create and non-destroy) objects and links."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivityNode" ordered="false"
          upperBound="-1" eType="#//activities/ActivityNode" containment="true" eOpposite="#//activities/ActivityNode/owningActivity">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The activity contains all activity nodes via this reference."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OperationExtension" eSuperTypes="#//Extension #//calls/Callable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An OperationExtension is a stand-in for an EOperation in our model. It is necessary because we cannot change the type EOperation. Thus, OperationExtension points to an EOperation but adds the reference to an Activity that describes the operations behavior."/>
      </eAnnotations>
      <eOperations name="NumberOfOutParams" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/uml2/1.1.0/GenModel">
          <details key="body" value="self.oclAsType(Callable).out->size() &lt;= 1"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="self.oclAsType(Callable).out->size() &lt;= 1"/>
        </eAnnotations>
        <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
          </eAnnotations>
        </eParameters>
        <eParameters name="context">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The cache of context-specific information."/>
          </eAnnotations>
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operation" ordered="false"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EOperation"
          volatile="true" transient="true" unsettable="true" derived="true" resolveProxies="false">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The EOperation whose behavior is defined by the Activity. The property is derived because the actual value is determined by the utility class OperationsExtensionOperation."/>
        </eAnnotations>
        <eAnnotations source="redefines" references="#//Extension/base"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" ordered="false"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EParameter"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The return value of the referenced operation."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivity" ordered="false"
          eType="#//activities/Activity" containment="true" eOpposite="#//activities/Activity/owningOperation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MatchingStoryNode" eSuperTypes="#//activities/StoryNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A MatchingStoryNode may only contain a MatchingPattern which does not change the graph. I.e., no element contained in this activity carries a create or destroy annotation. Thus, after executing a MatchingStoryNode, the underlying graph is guaranteed to be unchanged."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPattern" ordered="false"
          lowerBound="1" eType="#//patterns/MatchingPattern" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This MatchingPattern contained in this activity."/>
        </eAnnotations>
        <eAnnotations source="subsets" references="#//activities/StoryNode/storyPattern"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StoryNode" abstract="true" eSuperTypes="#//activities/ActivityNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An activity node containing a story pattern."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="forEach" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Specifies whether just one match should be found for the contained pattern (forEach  = false) or whether all matches should be found (forEach = true)."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="storyPattern" ordered="false"
          lowerBound="1" eType="#//patterns/StoryPattern" changeable="false" volatile="true"
          transient="true" derived="true">
        <eAnnotations source="union"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StructuredNode" eSuperTypes="#//activities/ActivityNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A structured node is a node that contains several other activities."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActivityNode" ordered="false"
          upperBound="-1" eType="#//activities/ActivityNode" containment="true" eOpposite="#//activities/ActivityNode/owningActivityNode">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="All subnodes which are contained in this structured node."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="EdgeGuard">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This enum is used to model different kinds of activity edges. "/>
      </eAnnotations>
      <eLiterals name="NONE">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="No guard, only one outgoing activity edge of this kind is supported per activity node. If an edge with EdgeGuard NONE is used, it must be the only edge leaving a state."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="SUCCESS" value="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Edge will be taken if execution of the souce activity node was successful, e.g., a story pattern was matched successfully. There must be another edge leaving the same node which is of kind FAILURE."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="FAILURE" value="2">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Edge will be taken if execution of the source activity node was not successful, e.g., a story pattern could not be matched. There must be another edge leaving the same node which is of kind SUCCESS"/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="EACH_TIME" value="3">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Edge may only leave a StoryNode whose forEach attribute is true. It will be taken for each match that can be identified for the story pattern in the foreach StoryNode. There must be another edge leaving the same node which is of kind END"/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="END" value="4">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Edge may only leave a StoryNode whose forEach attribute is true. It will be taken if no more fresh matches for the story pattern in the foreach node can be found."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="ELSE" value="5">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Complement to the BOOL guard, ELSE may only be used if at least one BOOL activity edge leaves the same state. The edge will be taken if none of the BOOL guards can be evaluated to true"/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="BOOL" value="6">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="An activity edge specifying a boolean guard using variables that have been previously used in the activity. Edge will be taken if the guardExpression of the activity edge evaluates to true. More than one BOOL edge is allowed to leave an activity node."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="EXCEPTION" value="7">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="An EXCEPTION edge will be taken if an exception of the  type defined by the ExceptionVariable connected to the activity edge occured while executing the source activity node of the edge. More than one edge of kind EXCEPTION is allowed to leave a node."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="FINALLY" value="8">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="An activity edge of kind FINALLY may only leave an activity node that has at least one other outgoing edge of kind EXCEPTION. The finally edge will be taken after the source node has been executed and after, possibly, the EXCEPTION edge has been taken."/>
        </eAnnotations>
      </eLiterals>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="JunctionNode" eSuperTypes="#//activities/ActivityNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A JunctionNode represents a pseudo-activity which is used for branching and merging the control flow in an activity. It is visualized by a diamond shaped figure."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StartNode" eSuperTypes="#//activities/ActivityNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The start node of an activity defines the starting point for the execution of the activity."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StatementNode" eSuperTypes="#//activities/ActivityNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A statement node is a node that just contains an expression defining its behavior. In combination with a textual expression, arbitrary souce code might be added by using StatementNodes."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statementExpression"
          ordered="false" lowerBound="1" eType="#//expressions/Expression" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The expression which defines the behavior of this StatementNode."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StopNode" eSuperTypes="#//activities/ActivityNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="At a StopNode, the execution of an activity terminates. If the activity specifies any out-parameters, they have to be bound to a return expression."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="flowStopOnly" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="true if subactivity is stopped, but not the whole control flow"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnValue" ordered="false"
          eType="#//expressions/Expression" changeable="false" volatile="true" transient="true"
          derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Convenience method when dealing with activities that implement an EOperation. In this case, only one out parameter is supported. This attributes then returns the first out parameter."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="returnValues" ordered="false"
          upperBound="-1" eType="#//expressions/Expression" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Defines the return values of the activity. These return values will be assigned to the out-parameters."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActivityCallNode" eSuperTypes="#//activities/ActivityNode #//calls/Invocation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The ActivityCallNode is a special ActivityNode which represents the calling of another story diagram within an activity.&#xD;&#xA;To support polymorphic dispatching, multiple activities can be assigned to it (all of which must have the same call signature, i.e. matching in and out parameters). All assigned activities are then called in the given order and the first one whose precondition is fulfilled is executed (Chain of Responsibilty)."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="calledActivity" lowerBound="1"
          upperBound="-1" eType="#//activities/Activity">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="References all activities that are to be considered for the polymorphic dispatching of the call. All activities must have the same call signature."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ModifyingStoryNode" eSuperTypes="#//activities/StoryNode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A ModifyingStoryNode contains a story pattern which may change the underlying graph upon execution."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRule" ordered="false"
          lowerBound="1" eType="#//patterns/StoryPattern" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The story pattern contained in this ModifyingStoryNode."/>
        </eAnnotations>
        <eAnnotations source="subsets" references="#//activities/StoryNode/storyPattern"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eSubpackages name="expressions" nsURI="http://ns.storydriven.org/sdm/activities/expressions/0.1.0"
        nsPrefix="sdmae">
      <eClassifiers xsi:type="ecore:EClass" name="ExceptionVariableExpression" eSuperTypes="#//expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents the value of an exception variable declared as a transition guard (the guard of an activity edge)."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="exceptionVariable"
            ordered="false" lowerBound="1" eType="#//activities/ExceptionVariable">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Specifies the exception variable that this expression refers to. If you have an activity edge that catches an exception e, then this expression can represent the reference e."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="expressions" nsURI="http://ns.storydriven.org/sdm/expressions/0.1.0"
      nsPrefix="sdme">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The base package for all expressions which can be used for modeling activities&#xD;&#xA;and patterns."/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EEnum" name="LogicOperator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the operators for binary logic expressions. The unary logic expression representing negated expressions is reflected by the NotExpression."/>
      </eAnnotations>
      <eLiterals name="AND"/>
      <eLiterals name="OR" value="1"/>
      <eLiterals name="XOR" value="2"/>
      <eLiterals name="IMPLY" value="3"/>
      <eLiterals name="EQUIVALENT" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ComparingOperator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the operators for comparing expressions."/>
      </eAnnotations>
      <eLiterals name="LESS"/>
      <eLiterals name="LESS_OR_EQUAL" value="1"/>
      <eLiterals name="EQUAL" value="2"/>
      <eLiterals name="GREATER_OR_EQUAL" value="3"/>
      <eLiterals name="GREATER" value="4"/>
      <eLiterals name="UNEQUAL" value="5"/>
      <eLiterals name="REGULAR_EXPRESSION" value="6">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="For comparison of a String with a regular expression."/>
        </eAnnotations>
      </eLiterals>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="ArithmeticOperator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the operators for arithmetic expressions."/>
      </eAnnotations>
      <eLiterals name="PLUS"/>
      <eLiterals name="MINUS" value="1"/>
      <eLiterals name="TIMES" value="2"/>
      <eLiterals name="DIVIDE" value="3"/>
      <eLiterals name="MODULO" value="4"/>
      <eLiterals name="EXP" value="5">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="For formulas like a^b."/>
        </eAnnotations>
      </eLiterals>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TextualExpression" eSuperTypes="#//expressions/Expression">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents any expression in a textual language embedded into Story Diagrams, e.g. OCL or Java ."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expressionText" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Holds the expression, e.g. in OCL or Java."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="String representation of the used language which has to be unique. Examples are OCL and Java."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="languageVersion" ordered="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="String representation of the used language's version. The format is &lt;Major>.&lt;Minor>[.&lt;Revision>[.&lt;Build>]]&#xD;&#xA;Examples: 1.4 or 3.0.1 or 1.0.2.20101208."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralExpression" eSuperTypes="#//expressions/Expression">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents any literal, i.e. a value whose type is an EDataType. Literals are, for example, 5, 3.14, 'c', &quot;text&quot;, true."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" ordered="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="String representation of the value, e.g. &quot;5&quot;, &quot;3.14&quot;, &quot;c&quot;, &quot;text&quot;, or &quot;true&quot;."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="valueType" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The literal's type, e.g. EInt, EString, etc."/>
        </eAnnotations>
        <eAnnotations source="subsets" references="#//TypedElement/type"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NotExpression" eSuperTypes="#//expressions/Expression">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents a negated expression, e.g. NOT (a &lt; 5)."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="negatedExpression" ordered="false"
          lowerBound="1" eType="#//expressions/Expression" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents the operand of a NotExpression, e.g. a &lt; 5 in NOT (a &lt; 5)."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true"
        eSuperTypes="#//expressions/Expression">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents any binary expression like v &lt; 5 or x + 7."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="leftExpression" ordered="false"
          lowerBound="1" eType="#//expressions/Expression" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents the first operand of a binary expression, e.g. x in the expression x &lt; 5."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rightExpression" ordered="false"
          lowerBound="1" eType="#//expressions/Expression" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents the second operand of a binary expression, e.g. 5 in the expression x &lt; 5."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComparisonExpression" eSuperTypes="#//expressions/BinaryExpression">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents comparing expressions like a &lt; 5 or a >= 7."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
          lowerBound="1" eType="#//expressions/ComparingOperator">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Specifies the expression's comparing operator, e.g. &lt;, >=, !=."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ArithmeticExpression" eSuperTypes="#//expressions/BinaryExpression">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents arithmetic expressions like a + 5 or a * 7."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
          lowerBound="1" eType="#//expressions/ArithmeticOperator">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Specifies the expression's arithmetic operator, e.g. +, -, *, /, or MODULO."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryLogicExpression" eSuperTypes="#//expressions/BinaryExpression">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents binary, logic expressions like a AND b and a OR b."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" ordered="false"
          lowerBound="1" eType="#//expressions/LogicOperator">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Specifies the expression's logic operator, e.g. AND, OR, or XOR."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="#//TypedElement #//CommentableElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents any expression in an embedded textual language, e.g. OCL or Java. An expression's type is dynamically derived by an external mechanism (see TypedElement)."/>
      </eAnnotations>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="calls" nsURI="http://ns.storydriven.org/sdm/calls/0.1.0" nsPrefix="sdmc">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This package contains all classes for modeling calls to activities and EOperations&#xD;&#xA;from within an activity."/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Invocation" abstract="true" eSuperTypes="#//CommentableElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Superclass for invocations of behavior which is specified elsewhere, e.g. in methods (MethodCallExpression) or activities (ActivityCallNode). An invocation has one parameter binding for each parameter (in or out) of the called method/activity. For Callables which are contained in the model (i.e. Activities and OperationExtensions) the Invocation directly points to the callee. OpaqueCallables are directly referenced by (and contained in) the MethodCallExpressions."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameterBindings"
          upperBound="-1" eType="#//calls/ParameterBinding" containment="true" eOpposite="#//calls/ParameterBinding/invocation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="callee" ordered="false"
          eType="#//calls/Callable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterBinding" eSuperTypes="#//CommentableElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Binds a parameter to a certain value for a given invocation. The value of the parameter is represented by an expression."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpression" ordered="false"
          lowerBound="1" eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" ordered="false"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EParameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="invocation" ordered="false"
          lowerBound="1" eType="#//calls/Invocation" eOpposite="#//calls/Invocation/ownedParameterBindings"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OpaqueCallable" eSuperTypes="#//calls/Callable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An OpaqueCallable represents an external method which is not explicitly modeled (e.g. a method in an external library). Because it is not contained anywhere in the model it is directly referenced by and contained in the MethodCallExpression."/>
      </eAnnotations>
      <eAnnotations source="duplicates">
        <contents xsi:type="ecore:EReference" name="inParameter" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EParameter">
          <eAnnotations source="redefines" references="#//calls/Callable/inParameter"/>
        </contents>
        <contents xsi:type="ecore:EReference" name="outParameter" upperBound="-1"
            eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EParameter">
          <eAnnotations source="redefines" references="#//calls/Callable/outParameter"/>
        </contents>
      </eAnnotations>
      <eOperations name="NumberOfOutParams" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/uml2/1.1.0/GenModel">
          <details key="body" value="self.oclAsType(Callable).out->size() &lt;= 1"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="self.oclAsType(Callable).out->size() &lt;= 1"/>
        </eAnnotations>
        <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
          </eAnnotations>
        </eParameters>
        <eParameters name="context">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The cache of context-specific information."/>
          </eAnnotations>
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="callExpression" ordered="false"
          lowerBound="1" eType="#//calls/expressions/MethodCallExpression" eOpposite="#//calls/expressions/MethodCallExpression/opaqueCallable"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterExtension" eSuperTypes="#//Variable #//Extension">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents an EParameter and adds functionality to it, especially beiing subtype of Variable."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" ordered="false"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EParameter"
          volatile="true" transient="true" unsettable="true" derived="true" resolveProxies="false">
        <eAnnotations source="redefines" references="#//Extension/modelBase"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Callable" abstract="true" eSuperTypes="#//CommentableElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An entity which can be called by an Invocation. A Callable can have a number of (ordered) parameters which are either in or out parameters. In the case of activities, the number of in and out parameters is unbounded, whereas OperationExtensions and OpaqueCallables can only have one out parameter (This is enforced by an OCL constraint)."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="inParameter" upperBound="-1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EParameter">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The ordered set of in parameters of this Callable. The parameters will not be contained in this reference, if parameters have to be contained in the callable, they also have to be added to the containedParameters reference."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outParameter" upperBound="-1"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EParameter">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The ordered set of out parameters of this Callable. The parameters will not be contained in this reference, if parameters have to be contained in the callable, they also have to be added to the containedParameters reference."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containedParameters"
          ordered="false" upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EParameter"
          containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="This reference is used to contain the parameters of a Callable if they are not already contained in another container. If the parameter is contained in another container as it is the case for parameters of a EOperation, they must not be added to this container!"/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eSubpackages name="expressions" nsURI="http://ns.storydriven.org/sdm/calls/expressions/0.1.0"
        nsPrefix="sdmce">
      <eClassifiers xsi:type="ecore:EClass" name="MethodCallExpression" eSuperTypes="#//expressions/Expression #//calls/Invocation">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A MethodCallEpression represents the direct invocation of a method. This can either be a method which is explicitly modeled as an EOperation in a class diagram (referenced by the OperationExtension) or an unmodeled method in an external library (referenced by an OpaqueCallable). Therefore, a MethodCallExpression references either an OperationExtension (indirectly via the callee role between Invocation and Callable) or an OpaqueCallable."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
            eType="#//expressions/Expression" containment="true">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="A MethodCallExpression references an expression instead of a target object to allow the determination of the call target by an expression. This can be handy when a method should be called e.g. on the return value of another method (as in a.b().c() ). Then the method call of c() would be modeled by a MethodCallExpression with the callExpression a.b(), which again is a MethodCallExpression itself."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="opaqueCallable" ordered="false"
            eType="#//calls/OpaqueCallable" containment="true" eOpposite="#//calls/OpaqueCallable/callExpression">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="This containment reference is a helper construct because the OpaqueCallable has to be contained somewhere. A MethodCallExpression (being an Invocation) could also reference an OpaqueCallable (being a Callable) via the callee reference but then the OpaqueCallable would not be contained anywhere in the model."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ParameterExpression" eSuperTypes="#//expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="An Expressions that represents a parameter value, e.g. the value of an Activity's parameter."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" ordered="false"
            eType="#//calls/ParameterExtension"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="patterns" nsURI="http://ns.storydriven.org/sdm/patterns/0.1.0"
      nsPrefix="sdmp">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This package contains all classes for modeling story patterns that may be &#xD;&#xA;embedded into StoryActivityNodes of an Activity."/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectVariable" eSuperTypes="#//patterns/AbstractVariable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An ObjectVariable holds a value of a complex type which is defined by an EClass. "/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingLink" ordered="false"
          upperBound="-1" eType="#//patterns/AbstractLinkVariable" eOpposite="#//patterns/AbstractLinkVariable/source"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkOrderConstraint"
          upperBound="-1" eType="#//patterns/LinkConstraint" containment="true" eOpposite="#//patterns/LinkConstraint/referencingObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingSemantics" ordered="false"
          lowerBound="1" eType="#//patterns/BindingSemantics" defaultValueLiteral="MANDATORY">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The binding semantics defines whether the object must be matched for a successful application of the containing story pattern, whether it must not be matched or whether it is optional, i.e., it will be bound if it can be bound but that does not affect the success of matching the story pattern."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingOperator" ordered="false"
          lowerBound="1" eType="#//patterns/BindingOperator" defaultValueLiteral="CHECK_ONLY">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The binding operator defines whether this object will be matched, created or destroyed by the story pattern."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributeAssignment"
          upperBound="-1" eType="#//patterns/AttributeAssignment" containment="true"
          eOpposite="#//patterns/AttributeAssignment/objectVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClass">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The type of this ObjectVariable, given as an EClass."/>
        </eAnnotations>
        <eAnnotations source="subsets" references="#//TypedElement/type"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractVariable" abstract="true"
        eSuperTypes="#//Variable #//NamedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Abstract super class for object and primitive variables."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" ordered="false"
          lowerBound="1" eType="#//patterns/StoryPattern" eOpposite="#//patterns/StoryPattern/variable"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingState" ordered="false"
          lowerBound="1" eType="#//patterns/BindingState" defaultValueLiteral="UNBOUND">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The binding state defines whether the variable is already bound or whether a match has to be obtained for it. The default value is &quot;unbound&quot;."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingExpression" ordered="false"
          eType="#//expressions/Expression" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A binding expression can be used to bind a variable in a different way than just by pattern matching. This way, for example, the return value of a call can be bound to a variable."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" upperBound="-1"
          eType="#//patterns/Constraint" containment="true" eOpposite="#//patterns/Constraint/objectVariable">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="All constraints which are defined for this variable. For a successful matching, all constraints for this variable must evaluate to true."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="incomingLink" ordered="false"
          upperBound="-1" eType="#//patterns/AbstractLinkVariable" eOpposite="#//patterns/AbstractLinkVariable/target"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BindingState">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The BindingState defines whether an object or link variable is already bound to a concrete value or not."/>
      </eAnnotations>
      <eLiterals name="UNBOUND">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="UNBOUND is the default value for this enum. If an object or link variable in a story pattern is unbound, a new match has to be obtained for that variable."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="BOUND" value="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A bound variable has already been bound to a concrete value. The concrete value has to be passed either as a parameter or it has to be bound in a previous activity. If, during the execution of a story pattern, a bound variable has no value, the execution of the story pattern fails."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="MAYBE_BOUND" value="2">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="A variable marked with maybe_bound indicates that it is unknown (or unimportant) at design time whether the variable is bound or not. If, during the execution of the pattern, the variable is not bound, an object is matched and bound to the variable. If it is already bound, it is not altered. If the variable is still unbound after this process, the matching fails (except for OPTIONAL variables)."/>
        </eAnnotations>
      </eLiterals>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Constraint">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A constraint represents a condition which must be fulfilled for a successful pattern matching. It can either be contained in the story pattern or in a variable. In the former case, the constraint is evaluated after the matching of the object structure is complete. It still has to be true for the pattern application to be sucessful (and therefore for creations and destructions to be carried out). If the constraint is contained in a variable, it constrains the matching of that variable, i.e., it is evaluated during the matching of the containing variable and has to be true for a successful matching. If the variable is an ObjectSetVariable, the constraint has to be true for every object in the set."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraintExpression"
          ordered="false" lowerBound="1" eType="#//expressions/Expression" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The constraintExpression defines the concrete condition of this constraint."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" ordered="false"
          eType="#//patterns/StoryPattern" eOpposite="#//patterns/StoryPattern/constraint">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The story pattern this constraint applies to."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" ordered="false"
          eType="#//patterns/AbstractVariable" eOpposite="#//patterns/AbstractVariable/constraint">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The object variable this constraint applies to."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractLinkVariable" abstract="true"
        eSuperTypes="#//NamedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Abstract super class for all kinds of link variables that represent links between two objects in a story pattern."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingSemantics" ordered="false"
          lowerBound="1" eType="#//patterns/BindingSemantics" defaultValueLiteral="MANDATORY">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The binding semantics defines whether the link must be matched for a successful application of the containing story pattern, whether it must not be matched or whether it is optional, i.e., it will be bound if it can be bound but that does not affect the success of matching the story pattern. The default value is &quot;mandatory&quot; (i.e., it must be matched)."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingOperator" ordered="false"
          lowerBound="1" eType="#//patterns/BindingOperator" defaultValueLiteral="CHECK_ONLY">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The binding operator defines whether this link will be matched, created or destroyed by the story pattern. The default value ist &quot;check_only&quot;, i.e., the link will be matched."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="source" ordered="false"
          lowerBound="1" eType="#//patterns/ObjectVariable" eOpposite="#//patterns/ObjectVariable/outgoingLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="secondLinkConstraint"
          ordered="false" upperBound="-1" eType="#//patterns/LinkConstraint" eOpposite="#//patterns/LinkConstraint/secondLink"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="firstLinkConstraint"
          ordered="false" upperBound="-1" eType="#//patterns/LinkConstraint" eOpposite="#//patterns/LinkConstraint/firstLink"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingState" ordered="false"
          lowerBound="1" eType="#//patterns/BindingState" defaultValueLiteral="UNBOUND">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The binding state defines whether the link is already bound or whether a match has to be obtained for it."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" ordered="false"
          lowerBound="1" eType="#//patterns/StoryPattern" eOpposite="#//patterns/StoryPattern/linkVariable"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="target" ordered="false"
          lowerBound="1" eType="#//patterns/AbstractVariable" eOpposite="#//patterns/AbstractVariable/incomingLink"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BindingSemantics">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The binding semantics defines which kind of match will be obtained for the object or link variable."/>
      </eAnnotations>
      <eLiterals name="MANDATORY">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="For a mandatory object or link variable, a match has to be found for a pattern to be successfully applied."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="NEGATIVE" value="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="If an object or link variable is marked as NEGATIVE, no match may be found for that object or link variable. If a match can be found, the execution of the story pattern fails."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="OPTIONAL" value="2">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="For an OPTIONAL object or link variable, the matching tries to find a match. If no match can be found, this does not affect the success of the pattern application. If a match can be found, the respective object or link is bound to the variable."/>
        </eAnnotations>
      </eLiterals>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BindingOperator">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The BindingOperator enum defines all possible operations for object and link variables. An object or link variable may be checked for existence be the story pattern (black object/link variable), it may be created (green object/link variable), or it may be destroyed (red object/link variable)."/>
      </eAnnotations>
      <eLiterals name="CHECK_ONLY">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="CHECK_ONLY is the default value of this enum. It requires an object or link variable just to be matched by the story pattern."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="CREATE" value="1">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="An object or link variable marked as CREATE will be created by the story pattern."/>
        </eAnnotations>
      </eLiterals>
      <eLiterals name="DESTROY" value="2">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="An object or link variable marked as DESTROY will be destroyed be the story pattern."/>
        </eAnnotations>
      </eLiterals>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkConstraint" eSuperTypes="#//ExtendableElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Link constraints (formerly known as MultiLinks in old meta-model) constrain the ordering of links of the referencingObject is a collection. This way objects can be required to have a certain position in the collection (FIRST, LAST, INDEX) or a certain ordering relative to each other (DIRECT_SUCCESSOR, INDIRECT_SUCCESSOR). While the first kind of LinkConstraint can be imposed upon a single link, the second kind requires two links that are related to each other (e.g., have the same referencingObject)."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The index of the linked object in the collection. The semantics of this attribute is only defined if the constraintType of the LinkConstraint is INDEX."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintType" ordered="false"
          lowerBound="1" eType="#//patterns/LinkConstraintType" defaultValueLiteral="DIRECT_SUCCESSOR">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The constraint type of the LinkConstraint."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="negative" ordered="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="If the negative attribute is true, the link constraint may not be fulfilled for the complete pattern application to be successful."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="firstLink" ordered="false"
          lowerBound="1" eType="#//patterns/AbstractLinkVariable" eOpposite="#//patterns/AbstractLinkVariable/firstLinkConstraint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencingObject" ordered="false"
          lowerBound="1" eType="#//patterns/ObjectVariable" eOpposite="#//patterns/ObjectVariable/linkOrderConstraint"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="secondLink" ordered="false"
          eType="#//patterns/AbstractLinkVariable" eOpposite="#//patterns/AbstractLinkVariable/secondLinkConstraint"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="LinkConstraintType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The LinkConstraintType represents the different uses of LinkConstraints. Objects can be required to have a certain position in their containing collection (FIRST, LAST, INDEX) or a certain ordering relative to each other (DIRECT_SUCCESSOR, INDIRECT_SUCCESSOR)."/>
      </eAnnotations>
      <eLiterals name="FIRST"/>
      <eLiterals name="LAST" value="1"/>
      <eLiterals name="DIRECT_SUCCESSOR" value="2"/>
      <eLiterals name="INDIRECT_SUCCESSOR" value="3"/>
      <eLiterals name="INDEX" value="4"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AttributeAssignment">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An AttributeAssignment is used to set the value of a certain attribute of an object. It references the attribute that is to be set and the value. The value can be an expression to allow for calculations or calls that determine the final value. AttributeAssignments are carried out during the final phase of pattern application, i.e. after the matching and destruction are completed."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The attribute whose value is set. It has to be an attribute of the objectVariable that contains the AttributeAssignment."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="valueExpression" ordered="false"
          lowerBound="1" eType="#//expressions/Expression" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The expression that determines the new value that is given to the attribute."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" ordered="false"
          lowerBound="1" eType="#//patterns/ObjectVariable" eOpposite="#//patterns/ObjectVariable/attributeAssignment"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ObjectSetVariable" eSuperTypes="#//patterns/ObjectVariable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents a set of objects of the same type that are represented by a single node.&#xD;&#xA;The context for contained Constraints and AttributeAssignments is every single object in the set. E.g., if the constraint is &quot;name = 'abc'&quot;, only objects with that name are matched and added to the set. The use of the binding operator &quot;CREATE&quot; is not defined for ObjectSetVariables, i.e., the sets can only be matched and deleted."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PrimitiveVariable" eSuperTypes="#//patterns/AbstractVariable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents a variable that holds a value of a primitive type, e.g. integer, boolean, String."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="classifier" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EDataType">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The type of the primitive variable which must be an EDataType."/>
        </eAnnotations>
        <eAnnotations source="subsets" references="#//TypedElement/type"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Path" eSuperTypes="#//patterns/AbstractLinkVariable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A path is a special link variable that specifies an indirect connection between two objects. That means, the connected objects have other links and objects &quot;between them&quot;. Exactly which types of links may be traversed during the matching of a path can be constrained by a path expression."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pathExpression" ordered="false"
          lowerBound="1" eType="#//expressions/Expression" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The path expression constrains the matching of the path variable during pattern application. It can determine which links may be matched when and how many times to reach the target object of the path from the source object."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LinkVariable" eSuperTypes="#//patterns/AbstractLinkVariable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A link variable represents one link between two object variables. It is typed over one of the associations between the classes of those objects. Because EMF only directly supports references, the two link ends are typed over these references. In case of a uni-directional association, only the targetEnd is typed. In case of a bi-directional association, the reference that types the source end is automatically determined."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEnd" ordered="false"
          eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference"
          volatile="true" transient="true" derived="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The source end of a link variable can only be determined when the link is typed over a bi-directional association. In this case, it points to the &quot;reverse&quot; direction of the association. If the reference is only uni-directional, the source end is null. The value of this attribute is derived automatically."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetEnd" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EReference">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="The target end points to the reference that types this direction of the link (the &quot;normal&quot; direction). This link end must be set always."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="qualifierExpression"
          ordered="false" eType="#//expressions/Expression" containment="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="If a link is typed over a qualified reference, a qualifier determines the key under which the object reachable via the link is stored. Because the qualifier can be set by an expression, it can either be a simple string or something more complex, e.g., a call like &quot;object.getName()&quot;."/>
        </eAnnotations>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContainmentRelation" eSuperTypes="#//patterns/AbstractLinkVariable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Specifies the containment of an object in a set (represented by a ContainerVariable). Will be displayed by a line having a circle with a plus inside at the end of the container (the source end of the link). A create modifier specifies that the object will be added to the container, delete that it will be removed, and none that it will be checked to be contained."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MatchingPattern" eSuperTypes="#//patterns/StoryPattern">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A MatchingPattern is a special kind of story pattern that does not change the underlying graph. Thus, no contained object or link may carry an create or destroy BindingOperator."/>
      </eAnnotations>
      <eOperations name="NoModifierInMatchingPattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eAnnotations source="http://www.eclipse.org/uml2/1.1.0/GenModel">
          <details key="body" value="self.objectVariable->forAll(v:ObjectVariable | v.modifier = Modifier::NONE) and self.linkVariable->forAll(v:LinkVariable | v.modifier = Modifier::NONE)"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="self.objectVariable->forAll(v:ObjectVariable | v.modifier = Modifier::NONE) and self.linkVariable->forAll(v:LinkVariable | v.modifier = Modifier::NONE)"/>
        </eAnnotations>
        <eParameters name="diagnostics" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The chain of diagnostics to which problems are to be appended."/>
          </eAnnotations>
        </eParameters>
        <eParameters name="context">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="The cache of context-specific information."/>
          </eAnnotations>
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eGenericType>
        </eParameters>
      </eOperations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ContainerVariable" eSuperTypes="#//patterns/ObjectVariable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents a single container, e.g. a Set or List. ContainmentRelations can be used to add or remove objects to or from this container.&#xD;&#xA;Every Constraint or AttributeAssignment can use the variable as a container (e.g., &quot;set->size() > 5&quot;)."/>
      </eAnnotations>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StoryPattern" eSuperTypes="#//CommentableElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A Story Pattern is a graph rewrite rule that may be embedded into a StoryActivityNode&#xD;&#xA;of an Activity."/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="variable" ordered="false"
          upperBound="-1" eType="#//patterns/AbstractVariable" containment="true"
          eOpposite="#//patterns/AbstractVariable/pattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="constraint" ordered="false"
          upperBound="-1" eType="#//patterns/Constraint" containment="true" eOpposite="#//patterns/Constraint/pattern">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="All constraints which are defined for this story pattern. For a successful matching, all constraints for this story pattern must evaluate to true."/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="linkVariable" upperBound="-1"
          eType="#//patterns/AbstractLinkVariable" containment="true" eOpposite="#//patterns/AbstractLinkVariable/pattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parentPattern" ordered="false"
          eType="#//patterns/StoryPattern" eOpposite="#//patterns/StoryPattern/containedPattern"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="containedPattern" ordered="false"
          upperBound="-1" eType="#//patterns/StoryPattern" containment="true" eOpposite="#//patterns/StoryPattern/parentPattern"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingSemantics" ordered="false"
          lowerBound="1" eType="#//patterns/BindingSemantics" defaultValueLiteral="MANDATORY"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="templateSignature" ordered="false"
          eType="#//templates/TemplateSignature" containment="true" eOpposite="#//templates/TemplateSignature/pattern"/>
    </eClassifiers>
    <eSubpackages name="expressions" nsURI="http://ns.storydriven.org/sdm/patterns/expressions/0.1.0"
        nsPrefix="sdmpe">
      <eClassifiers xsi:type="ecore:EClass" name="AttributeValueExpression" eSuperTypes="#//expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents the value of an object's attribute, e.g. obj.attr for an object obj and an attribute attr."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="object" ordered="false"
            lowerBound="1" eType="#//patterns/ObjectVariable">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Specifies the object variable whose attribute value is represented by this expression."/>
          </eAnnotations>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" ordered="false"
            lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EAttribute">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Specifies the object's attribute whose attribute value is represented by this expression."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ObjectVariableExpression" eSuperTypes="#//expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents the reference to an object in an expression, i.e. the value of an object variable."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="object" ordered="false"
            lowerBound="1" eType="#//patterns/ObjectVariable">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Specifies the object variable that holds the reference to be represented by this expression."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ObjectSetSizeExpression" eSuperTypes="#//expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents the number of elements in the set of objects that is represented by an object set variable. For example, if you have an object set variable mySet, then this expression would represent something like mySet.size(). The expression can be used to constrain the pattern application, e.g., to only a apply the pattern when at least two objects can be matched for the set."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="set" ordered="false"
            lowerBound="1" eType="#//patterns/ObjectSetVariable">
          <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
            <details key="documentation" value="Specifies the object set variable whose number of set elements is to be represented by this expression."/>
          </eAnnotations>
        </eStructuralFeatures>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="PrimitiveVariableExpression" eSuperTypes="#//expressions/Expression">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="Represents the value of a primitive variable, e.g., 5 or &quot;MyName&quot;."/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveVariable"
            ordered="false" lowerBound="1" eType="#//patterns/PrimitiveVariable"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="templates" nsURI="http://ns.storydriven.org/sdm/templates/0.1.0"
      nsPrefix="sdmt">
    <eClassifiers xsi:type="ecore:EClass" name="TemplateBinding" eSuperTypes="#//ExtendableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="boundParameter" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingExpression" ordered="false"
          lowerBound="1" eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="template" ordered="false"
          lowerBound="1" eType="#//templates/TemplateSignature" eOpposite="#//templates/TemplateSignature/templateBinding"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="propertyBinding" ordered="false"
          upperBound="-1" eType="#//templates/PropertyBinding" containment="true"
          eOpposite="#//templates/PropertyBinding/templateBinding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PropertyBinding" eSuperTypes="#//ExtendableElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="boundProperty" ordered="false"
          lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindingExpression" ordered="false"
          lowerBound="1" eType="#//expressions/Expression" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="templateBinding" ordered="false"
          lowerBound="1" eType="#//templates/TemplateBinding" eOpposite="#//templates/TemplateBinding/propertyBinding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TemplateSignature">
      <eStructuralFeatures xsi:type="ecore:EReference" name="templateBinding" ordered="false"
          upperBound="-1" eType="#//templates/TemplateBinding" containment="true"
          eOpposite="#//templates/TemplateBinding/template"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameter" ordered="false"
          upperBound="-1" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EClassifier"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" ordered="false"
          lowerBound="1" eType="#//patterns/StoryPattern" eOpposite="#//patterns/StoryPattern/templateSignature"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
