/*
* generated by Xtext
*/
package org.storydriven.modeling.expressions.common.ui.contentassist;

import org.storydriven.modeling.expressions.common.ui.contentassist.AbstractExpressionsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ExpressionsProposalProvider extends AbstractExpressionsProposalProvider {

}
