<?xml version="1.0" encoding="UTF-8"?>
<metricvalues:MetricValuesModel xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:metricvalues="http://metricvalues/1.0" minCompThreshold="0.25"
    maxMergeThreshold="1.0">
  <iterations number="1" curCompThreshold="1.0" curMergeThreshold="0.45" isMergeIteration="true">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 0 ProductSearch>" id="_t1k2AIP4EeC81IhLTZ23ZA">
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 2 PriceCalculator>" id="_t1k2DoP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.0/@componentCandidates.1"
        secondComponent="#//@iterations.0/@componentCandidates.2">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="2.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.013362055292000642"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.Instability" value="1.0"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="-1.4747247884148046E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.49439604580402374"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling" value="8.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.0/@componentCandidates.2"
        secondComponent="#//@iterations.0/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="2.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.013362055292000642"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.Instability" value="1.0"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="-1.4747247884148046E-4"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.49439604580402374"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling" value="8.0"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.0/@componentCandidates.0"
        secondComponent="#//@iterations.0/@componentCandidates.2">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="2.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.015453846672096767"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.0018892717596731689"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5717923268675804"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling" value="4.0"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.0/@componentCandidates.2"
        secondComponent="#//@iterations.0/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="2.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.01897486795981725"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.231437629169744"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5717923268675804"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling" value="4.0"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.0/@componentCandidates.1"
        secondComponent="#//@iterations.0/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping" value="1.0"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="2.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.5642021515717109"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.7873816994988189"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.564633697271347"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling" value="4.0"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality" value="1.0"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.0/@componentCandidates.0"
        secondComponent="#//@iterations.0/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping" value="1.0"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="2.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.7141158424317837"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.6845032609090572"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.564633697271347"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling" value="4.0"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping" value="1.0"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality" value="1.0"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="2" curCompThreshold="1.0" curMergeThreshold="0.45" isMergeIteration="true">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.1/@componentCandidates.0"
        secondComponent="#//@iterations.1/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.1/@componentCandidates.1"
        secondComponent="#//@iterations.1/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="3" curCompThreshold="1.0" curMergeThreshold="0.55" isMergeIteration="true">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.2/@componentCandidates.1"
        secondComponent="#//@iterations.2/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.2/@componentCandidates.0"
        secondComponent="#//@iterations.2/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="4" curCompThreshold="1.0" curMergeThreshold="0.65" isMergeIteration="true">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.3/@componentCandidates.1"
        secondComponent="#//@iterations.3/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.3/@componentCandidates.0"
        secondComponent="#//@iterations.3/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="5" curCompThreshold="1.0" curMergeThreshold="0.75" isMergeIteration="true">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.4/@componentCandidates.1"
        secondComponent="#//@iterations.4/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.4/@componentCandidates.0"
        secondComponent="#//@iterations.4/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="6" curCompThreshold="1.0" curMergeThreshold="0.85" isMergeIteration="true">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.5/@componentCandidates.1"
        secondComponent="#//@iterations.5/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.5/@componentCandidates.0"
        secondComponent="#//@iterations.5/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="7" curCompThreshold="1.0" curMergeThreshold="0.95" isMergeIteration="true">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.6/@componentCandidates.1"
        secondComponent="#//@iterations.6/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.6/@componentCandidates.0"
        secondComponent="#//@iterations.6/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="8" curCompThreshold="1.0" curMergeThreshold="1.05">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.7/@componentCandidates.1"
        secondComponent="#//@iterations.7/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.7/@componentCandidates.0"
        secondComponent="#//@iterations.7/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="9" curCompThreshold="0.9" curMergeThreshold="1.05">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.8/@componentCandidates.1"
        secondComponent="#//@iterations.8/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.8/@componentCandidates.0"
        secondComponent="#//@iterations.8/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="10" curCompThreshold="0.8" curMergeThreshold="1.05">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.9/@componentCandidates.1"
        secondComponent="#//@iterations.9/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.9/@componentCandidates.0"
        secondComponent="#//@iterations.9/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="11" curCompThreshold="0.7000000000000001" curMergeThreshold="1.05">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.10/@componentCandidates.1"
        secondComponent="#//@iterations.10/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.10/@componentCandidates.0"
        secondComponent="#//@iterations.10/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="12" curCompThreshold="0.6000000000000001" curMergeThreshold="1.05">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.11/@componentCandidates.1"
        secondComponent="#//@iterations.11/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.11/@componentCandidates.0"
        secondComponent="#//@iterations.11/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="13" curCompThreshold="0.5000000000000001" curMergeThreshold="1.05">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.12/@componentCandidates.1"
        secondComponent="#//@iterations.12/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.12/@componentCandidates.0"
        secondComponent="#//@iterations.12/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="14" curCompThreshold="0.40000000000000013" curMergeThreshold="1.05">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.13/@componentCandidates.1"
        secondComponent="#//@iterations.13/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.13/@componentCandidates.0"
        secondComponent="#//@iterations.13/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
  <iterations number="15" curCompThreshold="0.30000000000000016" curMergeThreshold="1.05">
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnxQYLgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 4 ProductsListView>" id="_t1ldFYP4EeC81IhLTZ23ZA">
        <requiredInterfaces/>
        <requiredInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidates classes="platform:/resource/Store12_Refactored/Store1.gast#_wFnKPILgEeC8KcVgiBxg9w platform:/resource/Store12_Refactored/Store1.gast#_wFnxQILgEeC8KcVgiBxg9w">
      <component name=" &lt;PC No. 6 ProductSearch PriceCalculator>" id="_SdOIUIP5EeC81IhLTZ23ZA">
        <providedInterfaces/>
        <providedInterfaces/>
      </component>
    </componentCandidates>
    <componentCandidatePairs firstComponent="#//@iterations.14/@componentCandidates.1"
        secondComponent="#//@iterations.14/@componentCandidates.0">
      <metricValues metricID="org.somox.metrics.Coupling"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="0.014407950982048705"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="8.708996404158441E-4"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
    <componentCandidatePairs firstComponent="#//@iterations.14/@componentCandidates.0"
        secondComponent="#//@iterations.14/@componentCandidates.1">
      <metricValues metricID="org.somox.metrics.Coupling" value="1.0"/>
      <metricValues metricID="org.somox.metrics.basic.ExternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.PackageMapping"/>
      <metricValues metricID="org.somox.metric.basic.AbstractTypesCount" value="3.0"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultMergeIndicatingMetric"
          value="-0.02671449606617292"/>
      <metricValues metricID="org.somox.metrics.basic.TotalTypesCount" value="6.0"/>
      <metricValues metricID="org.somox.metrics.Instability"/>
      <metricValues metricID="org.somox.metrics.Abstractness" value="0.5"/>
      <metricValues metricID="org.somox.metrics.SubsystemComponent"/>
      <metricValues metricID="org.somox.metrics.DMS" value="0.5"/>
      <metricValues metricID="org.somox.metrics.AdherenceToInterfaceCommunication"
          value="0.75"/>
      <metricValues metricID="org.somox.analyzer.simplemodelanalyzer.metrics.DefaultCompositionIndicatingMetric"
          value="0.2238662538483091"/>
      <metricValues metricID="org.somox.metrics.NameResemblance" value="0.5330941863358021"/>
      <metricValues metricID="org.somox.metrics.basic.InternalAccessesCount" value="4.0"/>
      <metricValues metricID="org.somox.metrics.basic.AfferentCoupling"/>
      <metricValues metricID="org.somox.metric.basic.EfferentCoupling"/>
      <metricValues metricID="org.somox.metrics.basic.InterfaceAccessesCount" value="3.0"/>
      <metricValues metricID="org.somox.metrics.DirectoryMapping"/>
      <metricValues metricID="org.somox.metrics.SliceLayerArchitectureQuality"/>
    </componentCandidatePairs>
  </iterations>
</metricvalues:MetricValuesModel>
