/*
* generated by Xtext
*/
package org.storydriven.modeling.expressions.ui.contentassist;

import org.storydriven.modeling.expressions.ui.contentassist.AbstractPathExpressionsProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PathExpressionsProposalProvider extends AbstractPathExpressionsProposalProvider {

}
