/*
 * generated by Xtext
 */
package org.storydriven.modeling.expressions;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PathExpressionsRuntimeModule extends org.storydriven.modeling.expressions.AbstractPathExpressionsRuntimeModule {

}
