/*
* generated by Xtext
*/
package org.storydriven.modeling.expressions.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class PathExpressionsTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
