<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pathbridge"
    nsURI="http://www.storydriven.org/modeling/expressions/pathbridge" nsPrefix="pathbridge">
  <eClassifiers xsi:type="ecore:EClass" name="PathExpressionBridge" eSuperTypes="../../org.storydriven.modeling/model/sdm.ecore#//expressions/Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pathExpression" eType="ecore:EClass ../src-gen/org/storydriven/modeling/expressions/PathExpressions.ecore#//PathExpression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
